# Helps catch spelling errors
name: Codespell

on:
  pull_request:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - uses: codespell-project/actions-codespell@94259cd8be02ad2903ba34a22d9c13de21a74461 # v2.0
        with:
          skip: .git,_artifacts,*.sum
          ignore_words_file: .codespellignore
          check_filenames: true
          check_hidden: true

