# add public code coverage reports
name: coverage

on:
  push:
    branches:
    - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

    - run: "make test-cover"

    - uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
      with:
        file: ./coverage.out
        fail_ci_if_error: true
