# add public code coverage reports
name: coverage

on:
  push:
    branches:
    - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

    - run: "make test-cover"

    - uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be # v4.3.1
      with:
        file: ./coverage.out
        fail_ci_if_error: true
