# add public code coverage reports
name: coverage

on:
  push:
    branches:
    - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

    - run: "make test-cover"

    - uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
      with:
        file: ./coverage.out
        fail_ci_if_error: true
