# Check for broken links
name: Link-check

on:
  push:
    paths:
      - "docs/**"
    branches:
      - main
  pull_request:
    paths: "docs/**"

jobs:
  lint_docs:
    name: Broken Links
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

    - uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec # v1.0.15
      with:
        use-quiet-mode: 'yes'
        config-file: ".markdownlinkcheck.json"
